# Generated by Django 4.2 on 2023-04-21 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='storage.user', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='box_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='storage.box', verbose_name='Бокс'),
        ),
    ]
