# Generated by Django 4.2 on 2023-04-21 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_alter_box_user_id_alter_transferrequest_box_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='box',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='transferrequest',
            old_name='box_id',
            new_name='box',
        ),
    ]
