# Generated by Django 4.2 on 2023-04-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_rename_user_id_box_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='from_owner',
            field=models.BooleanField(null=True, verbose_name='Представитель заказчика'),
        ),
    ]
