# Generated by Django 4.2 on 2023-04-22 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_user_from_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='size',
        ),
        migrations.AddField(
            model_name='box',
            name='weight',
            field=models.IntegerField(null=True, verbose_name='Вес'),
        ),
    ]
