# Generated by Django 4.2 on 2023-04-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_remove_box_size_box_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferrequest',
            name='is_call_needed',
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='time_arrive',
            field=models.CharField(max_length=10, null=True, verbose_name='Желаемое время'),
        ),
    ]
